const keyboardEnCapsShiftKeys = {
  "Backquote": "±",
  "Digit1": "!",
  "Digit2": "@",
  "Digit3": "#",
  "Digit4": "$",
  "Digit5": "%",
  "Digit6": "^",
  "Digit7": "&",
  "Digit8": "*",
  "Digit9": "(",
  "Digit0": ")",
  "Minus": "_",
  "Equal": "+",
  "Backspace": "Backspace",
  "Tab": "Tab",
  "KeyQ": "Q",
  "KeyW": "W",
  "KeyE": "E",
  "KeyR": "R",
  "KeyT": "T",
  "KeyY": "Y",
  "KeyU": "U",
  "KeyI": "I",
  "KeyO": "O",
  "KeyP": "P",
  "BracketLeft": "{",
  "BracketRight": "}",
  "Backslash": "|",
  "CapsLock": "CapsLock",
  "KeyA": "A",
  "KeyS": "S",
  "KeyD": "D",
  "KeyF": "F",
  "KeyG": "G",
  "KeyH": "H",
  "KeyJ": "J",
  "KeyK": "K",
  "KeyL": "L",
  "Semicolon": ":",
  "Quote": "\"",
  "Enter": "Enter",
  "ShiftLeft": "Shift",
  "IntlBackslash": "~",
  "KeyZ": "Z",
  "KeyX": "X",
  "KeyC": "C",
  "KeyV": "V",
  "KeyB": "B",
  "KeyN": "N",
  "KeyM": "M",
  "Comma": "<",
  "Period": ">",
  "Slash": "?",
  "ArrowUp": "&#9650;",
  "ShiftRight": "Shift",
  "Fn": "Fn",
  "ControlLeft": "Ctrl",
  "LeftOpt": "Opt",
  "LeftCmd": "Cmd",
  "Space": " ",
  "RightCmd": "Cmd",
  "RightOpt": "Opt",
  "ArrowLeft": "&#9668;",
  "ArrowDown": "&#9660;",
  "ArrowRight": "&#9658;"
}

// const keyboardEnCapsShiftKeysArray = Object.keys(keyboardEnCapsShiftKeys);

export default keyboardEnCapsShiftKeys;